export const WDS_TEXT_FAMILY_BASE = 'Montserrat'
export const WDS_TEXT_WEIGHT_REGULAR = '400'
export const WDS_TEXT_WEIGHT_MEDIUM = '500'
export const WDS_TEXT_WEIGHT_DEMI = '600'
export const WDS_TEXT_WEIGHT_BOLD = '700'
export const WDS_TEXT_STYLE_NORMAL = 'normal'
export const WDS_TEXT_STYLE_ITALIC = 'italic'
